- hosts: deploy_ip
  gather_facts:  false
  vars:
    - work_dir: "{{ inventory_dir }}/Stepfiles/brainconfig"
    - base_service_dir: "{{ inventory_dir }}/Stepfiles/baseservice"
  tasks:
    - name: helmfile-A deploy cluster
      shell: "chdir={{ inventory_dir }}/Stepfiles/cloudbrain/ helmfile -f  helmfile-A.yaml apply  >>  ~/UADT/mods/logs/config/runtime 2>&1 "

    - name: wait for task A
      pause: seconds=600

    - name: helmfile-B deploy cluster
      shell: "chdir={{ inventory_dir }}/Stepfiles/cloudbrain/ helmfile -f  helmfile-B.yaml apply  2>&1"

    - name: pip install yaml
      command: "chdir={{ inventory_dir }}/Stepfiles/brainconfig/  sudo pip install --no-index --find-links=. ruamel.yaml"
      args:
        creates: "{{ work_dir }}/pre"


    - name: skip pip install and host
      command: touch {{ work_dir }}/pre

#    - name: monitor port healthy
#      shell: python3 {{ work_dir }}/config-sync/watch_dog.py {{ client.0.1 }} >>  ~/UADT/mods/logs/config/runtime 2>&1

    - name: wait for task B
      pause: seconds=600

    - name: kong config
      command: "python3 {{ work_dir }}/config-sync/kong_standalone.py  https://{{ deployip }}:32444/ {{ ingressdomain }} {{ namespace }} {{ work_dir }}/config-sync"


    - name: add minio server address
      command: mc config host add common-minio-s3  http://{{ deployip }}:30003 'cloud@uisee.com' 'cloud!234'


    - name: add bucket
      shell:
        cmd: |
          mc mb common-minio-s3/console-vehicles
          mc mb common-minio-s3/maps
          mc mb common-minio-s3/utc-map-gl
          mc mb common-minio-s3/ota
          mc policy set public common-minio-s3/console-vehicles
          mc policy set public common-minio-s3/maps
          mc policy set public common-minio-s3/utc-map-gl
          mc cp  {{ base_service_dir }}/minio/utc-map-gl/*  common-minio-s3/utc-map-gl/
          mc cp {{ base_service_dir }}/minio/console-vehicles/*  ucloud-minio-s3/console-vehicles/



    - name: nacos config
      command: python3 {{ work_dir }}/config-sync/nacos.py  {{ deployip }}:31205  {{ work_dir }}/config-sync {{ namespace }}

    - name: emqx config
      command: "python3 {{ work_dir }}/config-sync/emqx.py  {{ deployip }} {{ work_dir }}/config-sync"

#    - name: console test
#      command: python3 {{ work_dir }}/config-sync/watch_console.py  null {{ ingressdomain }}

    - name: console config
      shell: python3 {{ work_dir }}/config-sync/console_standalone.py  https://{{ ingressdomain }}/  {{ consoleinitproject }}  {{ work_dir }}/config-sync >>  ~/UADT/mods/logs/config/runtime 2>&1


