---
- hosts: deploy_ip
  tasks:
    - name: get cloudbrain image file
      shell: sudo docker load -i {{ inventory_dir }}/Playbooks/images/cloudbrain_images.tar

    - name: rm -rf charts.txt
      command: rm -rf {{ inventory_dir }}/Stepfiles/cloudbrain/charts.txt

    - name: upload image/chart to harbor
      command: "python3 {{ inventory_dir }}/Stepfiles/cloudbrain/tag.py {{ deployip }}:31150 {{ inventory_dir }}/Stepfiles/cloudbrain/    {{ inventory_dir }}/Playbooks/images/cloudbrain/chart/  "

    - name: configure the service config file
      command: bash {{ inventory_dir }}/Stepfiles/cloudbrain/change_harbor_registry.sh  {{ deployip }}:31150

    - name: change helmfile registry
      shell: sed -i "s%https://reg.uisee.ai%http://{{ deployip }}:31150%g"  {{ inventory_dir }}/Stepfiles/cloudbrain/helmfile.yaml


    - name: create  k8s  serct
      command: kubectl create secret docker-registry docker-reg-secret --docker-server={{ deployip }}:31150 --docker-username=admin --docker-password=uisee123.
      args:
        creates: "{{ inventory_dir }}/Stepfiles/cloudbrain/docker-key-ready"

    - name: helmfile deploy cluster
      shell: touch {{ inventory_dir }}/Stepfiles/cloudbrain/docker-key-ready

    - name: change harbor registry
      shell: "chdir={{ inventory_dir }}/Stepfiles/cloudbrain/ bash change_harbor_registry.sh {{ deployip }}:31150"

    - name: update
      shell: helm repo update

    # helm 需要指定crt文件  https://helm.sh/zh/docs/helm/helm/
    # $KUBECONFIG	设置Kubernetes的可选配置文件(默认是"~/.kube/config")
    # $HELM_KUBECAFILE	设置Kubernetes证书机构文件
    # $HELM_KUBECONTEXT	设置kubeconfig上下文的名称


    - name: helmfile deploy cluster
      shell: "chdir={{ inventory_dir }}/Stepfiles/cloudbrain/ helmfile -e  default apply"



