---
- hosts: deploy_ip
  tasks:

    - name: load and push openebs images
      command: sudo bash {{ inventory_dir }}/Stepfiles/openebs/openebsImage.sh {{ deployip }} {{ inventory_dir }}/Stepfiles/openebs/


- hosts: server
  tasks:
    - name: pull openebs images
      shell:
        cmd: |
          sudo docker pull {{ deployip }}:31150/openebs/node-disk-operator:1.8.0
          sudo docker tag {{ deployip }}:31150/openebs/node-disk-operator:1.8.0  openebs/node-disk-operator:1.8.0
          sudo docker pull {{ deployip }}:31150/openebs/node-disk-manager:1.8.0
          sudo docker tag {{ deployip }}:31150/openebs/node-disk-manager:1.8.0  openebs/node-disk-manager:1.8.0
          sudo docker pull {{ deployip }}:31150/openebs/node-disk-exporter:1.8.0
          sudo docker tag {{ deployip }}:31150/openebs/node-disk-exporter:1.8.0  openebs/node-disk-exporter:1.8.0
          sudo docker pull {{ deployip }}:31150/openebs/provisioner-localpv:3.1.0
          sudo docker tag  {{ deployip }}:31150/openebs/provisioner-localpv:3.1.0  openebs/provisioner-localpv:3.1.0

- hosts: deploy_ip
  tasks:
    - name: openebs hostpath
      command: sudo kubectl apply -f {{ inventory_dir }}/Stepfiles/openebs/openebs.yaml