'''
       1.配置文件中的端口和密码不要变成数字
       2.配置之后要是部署机的新旧地址不一致会断网（看不见prettytable输出）
       3.所有主机用户名必须一致（该用户要存在sudo列表中）
       4. 把部署机器放在配置文件最前面 以便匹配
       5. 配置文件deploy_ip写last_address 的 
       6. Dns server 用逗号分割
       7.主机名不能出现下划线（横杠可以）
'''
hosts:
- last_address: 172.16.42.141
  new_address: 172.16.42.141/24
  hostname: k8s-master1
  ssh_port: '22'
  username: wlw
  password: '123'
  dns_server: 172.16.42.141,172.16.42.142,172.16.42.143
  gateway: 172.16.42.3
  interface: ens33
  master: true
  deploy: true
  deploy_ip: 172.16.42.141

- last_address: 172.16.42.132
  new_address: 172.16.42.142/24
  hostname: k8s-master2
  ssh_port: '22'
  username: wlw
  password: '123'
  dns_server: 172.16.42.141,172.16.42.142,172.16.42.143
  gateway: 172.16.42.3
  interface: ens33
  master: true
  deploy: false
  deploy_ip: 172.16.42.141
- last_address: 172.16.42.133
  new_address: 172.16.42.143/24
  hostname: k8s-master3
  ssh_port: '22'
  username: wlw
  password: '123'
  dns_server: 172.16.42.141,172.16.42.142,172.16.42.143
  gateway: 172.16.42.3
  interface: ens33
  master: true
  deploy: false
  deploy_ip: 172.16.42.141


- last_address: 172.16.42.135
  new_address: 172.16.42.145/24
  hostname: k8s-node2
  ssh_port: '22'
  username: wlw
  password: '123'
  dns_server: 172.16.42.141,172.16.42.142,172.16.42.143
  gateway: 172.16.42.3
  interface: ens33
  master: false
  deploy: false
  deploy_ip: 172.16.42.141


