mongodb:
  resources:
    requests:
      cpu: 40m
      memory: 120Mi
    limits:
      cpu: 80m
      memory: 200Mi

resources:
  requests:
    cpu: 50m
    memory: 200Mi
  limits:
    cpu: 2000m
    memory: 4000Mi

service:
  type: NodePort

ingress:
  enabled: false
