hosts:
- last_address: 172.16.42.131
  new_address: 172.16.42.131/24
  hostname: k8s-master1
  ssh_port: 22
  username: wlw
  password: 123
  dns_server: 8.8.8.8
  gateway: 172.16.42.3
  interface: ens33
  master: true
  deploy: true
  deploy_ip: 172.16.42.131


  #记得修改openebs的副本数 在cstor-sc.yaml中
