initasks:
     -   log: "mods/services/config/ipcheck/ipLastfail.log"
         sh: "mods/services/config/sh/check_ip.sh"
         error_message: 'The ip address is unreachable'
         task_id: 'checkip'
         vars: ['last_address']
     -   log: "mods/services/config/portcheck/ssh_fail.log"
         sh: "mods/services/config/sh/ssh.sh"
         error_message: 'SSH port is unreachable'
         task_id: 'checkPort'
         vars: ['last_address','ssh_port']
     -   log: "mods/services/config/expectcheck/expectfail.log"
         sh: "mods/services/config/sh/expect.sh"
         error_message: 'expect exec failed'
         task_id: 'expect_ip'
         vars: ['username','password','last_address','new_address','gateway','dns_server','interface','deploy_ip','hostname']
     -   log: "mods/services/config/sshcopycheck/sshcopyfail.log"
         sh: "mods/services/config/sh/ssh-copy-id.sh"
         error_message: 'ssh-key copy failed'
         task_id: 'ssh-copy'
         vars: ['username','last_address','password']
     -   log: "mods/services/config/ansiblecheck/ansiblefail.log"
         sh: "mods/services/config/sh/ansibleInstall.sh"
         error_message: 'Pip install Ansible install process is failed'
         task_id: 'ansible-install'
         vars: ['last_address','deploy_ip']
ansibletasks:
     -   log: "mods/ansible/config/Stepfiles/getinfo/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/getSysinfo.yaml'
     -   log: "mods/ansible/config/Stepfiles/apt/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/apt.yaml'
     -   log: "mods/ansible/config/Stepfiles/ntp/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/ntp.yaml'
     -   log: "mods/ansible/config/Stepfiles/basetools/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/baseTools.yaml'
#     -   log: "mods/ansible/config/Stepfiles/dns/Success.log"
#         playbookfile: 'mods/ansible/config/Playbooks/dns.yaml'
     -   log: "mods/ansible/config/Stepfiles/hosts/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/hosts.yaml'
     -   log: "mods/ansible/config/Stepfiles/docker/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/docker.yaml'
     -   log: "mods/ansible/config/Stepfiles/harbor/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/harbor.yaml'
     -   log: "mods/ansible/config/Stepfiles/k8s/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/k8s.yaml'
     -   log: "mods/ansible/config/Stepfiles/openebs/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/openebs.yaml'
     -   log: "mods/ansible/config/Stepfiles/helm/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/helm.yaml'
     -   log: "mods/ansible/config/Stepfiles/k9s/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/k9s.yaml'
     -   log: "mods/ansible/config/Stepfiles/cloudimage/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/cloudImage.yaml'
     -   log: "mods/ansible/config/Stepfiles/cloudbrain/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/cloudBrain.yaml'
     -   log: "mods/ansible/config/Stepfiles/baseservice/ingress-nginx/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/ingressNginx.yaml'
     -   log: "mods/ansible/config/Stepfiles/baseservice/kong/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/kong.yaml'
     -   log: "mods/ansible/config/Stepfiles/baseservice/minio/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/minio.yaml'
     -   log: "mods/ansible/config/Stepfiles/baseservice/nacos/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/nacos.yaml'
     -   log: "mods/ansible/config/Stepfiles/baseservice/observability/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/observability.yaml'
     -   log: "mods/ansible/config/Stepfiles/baseservice/kruise/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/kruise.yaml'
     -   log: "mods/ansible/config/Stepfiles/deploycloud/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/deployCloud.yaml'
     -   log: "mods/ansible/config/Stepfiles/brainconfig/Success.log"
         playbookfile: 'mods/ansible/config/Playbooks/brainConfig.yaml'
#     -   log: "mods/ansible/config/Stepfiles/istio/Success.log"
#         playbookfile: 'mods/ansible/config/Playbooks/istio.yaml'